version: '3'
volumes:
  data-container:

services:
  nginx:
   container_name: some-nginx
   image: nginx:alpine
   restart: always
   ports:
   - 8123:80
   - 8124:443
   volumes:
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
   - ./nginx/nginx.crt:/etc/ssl/nginx.crt
   - ./nginx/nginx.key:/etc/ssl/nginx.key
   - ./nginx/dhparam.pem:/etc/ssl/dhparam.pem
   - ./nginx/index.html:/usr/share/nginx/html/index.html
   depends_on:
   - app

  mysql:
   container_name: some-mysql
   image: mysql/mysql-server:5.7
   volumes:
   - data-container:/var/lib/mysql/
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: hellokoding
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always
  
  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql